# Adapted from https://gist.githubusercontent.com/jeremyckahn/bcfe074d774b2e75ad990fcb30c7a410/raw/f046128cba59d2f7d4e0d0e512e56bea9f54f8d9/deploy-farmhand-go-to-itch.yml

name: godot-ci

on:
  push:
    branches: [ main ]

env:
  EXPORT_NAME: SurviveTheIsland
  GODOT_VERSION: 3.4.4

jobs:
  export-web:
    name: Web Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:3.4.4
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable

      - name: Web Build
        env:
          SILENT_WOLF_API_KEY: ${{ secrets.SILENT_WOLF_API_KEY }}
        run: |
          echo $SILENT_WOLF_API_KEY >> api_key.env
          mkdir -v -p build/web
          godot -v --export "HTML5" ./build/web/index.html

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: web
          path: build/web

      - name: Install rsync 📚
        run: |
          apt-get update && apt-get install -y rsync

      - name: Publish to itch.io
        uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
          CHANNEL: web
          ITCH_GAME: survive-the-island
          ITCH_USER: MurphysDad
          PACKAGE: build/web

      - name: Notify Discord Channel
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@0.3.0
        with:
          args: 'See the latest version of the game: https://murphysdad.itch.io/survive-the-island'
